### ISSUE TITLE
Add Lnurl metadata to payment list item

### ISSUE THREAD

**Issue by roeierez** [breez/c-breez#112]
We want to add the lnurl metadata to the payment list the same way we do in Breez.
Also populate the list item title in these cases.

**Comment by roeierez** [comment]
@erdemyerebasmaz  Can we close this?

**Comment by erdemyerebasmaz** [comment]
> #### Suggestions: (@ok300)
> * Add domain information to external payment info; If title and description are equal to each other, display domain as payment title.

@roeierez yes, it can be closed. I had this suggestion which was not discussed.

**Comment by roeierez** [comment]
For now let's implement it if it is implemented in breez mobile. Otherwise let's close.

**Comment by erdemyerebasmaz** [comment]
> For now let's implement it if it is implemented in breez mobile. Otherwise let's close.

No, it's the same on breez mobile for majority of instances, mainly lnurl payments & withdraws.
