### ISSUE TITLE
Integrate Send to on-chain

### ISSUE THREAD

**Issue by roeierez** [breez/c-breez#148]
Depends on:
- https://github.com/breez/breez-sdk/issues/99
- https://github.com/breez/breez-sdk/issues/100

Tasks:
- [ ]  UI refactor, separate widgets for:
    - Send to BTC Address: Reverse Swap
    - Unexpected Funds: Sweep    
- [ ]  Handling scanned BTC addresses
- [ ]  Integrate [Expose txid in sweep bindings](https://github.com/breez/breez-sdk/pull/478) changes

**Comment by erdemyerebasmaz** [comment]
Depends on:
- [Send to on-chain: add ReverseSwapInfo API #99](https://github.com/breez/breez-sdk/issues/99)
- [Send to on-chain: add NewReverseSwap API #100](https://github.com/breez/breez-sdk/issues/100)
