### ISSUE TITLE
Transaction fee is wrong in unexpected funds

### ISSUE THREAD

**Issue by roeierez** [breez/c-breez#329]
The transaction fee is sat per byte but we show it as absolute fee, see screenshot:

![txfee](https://user-images.githubusercontent.com/5394889/210496225-c7e91056-7f86-4930-9e23-5c7cf4c81cf3.jpeg)

**Comment by erdemyerebasmaz** [comment]
@ademar111190 Please disable fee options the user can't afford or add a WarningBox and disable the Confirm button, whichever is more convenient.
