### ISSUE TITLE
Failed to receive: No open channel found 

### ISSUE THREAD

**Issue by kingonly** [breez/c-breez#408]
Logs: https://drive.google.com/file/d/1mfHj36rL5P1u7GcycOdJ88OaM4viD_ra/view?usp=drivesdk

**Comment by roeierez** [comment]
Should be fixed when this is merged: https://github.com/Blockstream/greenlight/pull/79

**Comment by roeierez** [comment]
fixed by https://github.com/breez/breez-sdk/pull/93
