### ISSUE TITLE
Closed Channel dialog 

### ISSUE THREAD

**Issue by kingonly** [breez/c-breez#410]
Should look like Breez Mobile, not like a payment
![Screenshot_2023-01-21-16-30-46-90_9a3a9060ca72a38f8a1fec1d0c1a640e](https://user-images.githubusercontent.com/31890660/213871507-ce03bdc2-a571-475a-9006-7c471a498a62.jpg)

**Comment by ademar111190** [comment]
I did start working on it; I did open this PR in draft mode: https://github.com/breez/c-breez/pull/460
It seems there is some information we don't yet o the SDK, such as:
- closeChannelTxUrl
- closeChannelTx
- pendingExpirationHeight
- hoursToExpire
- remoteCloseChannelTxUrl
- remoteCloseChannelTx

**Comment by roeierez** [comment]
@ademar111190 should we close this?

**Comment by ademar111190** [comment]
I believe we can close @roeierez as long as we have an issue tracking the missing fields.
