### ISSUE TITLE
Font sizes are smaller in payment details dialog 

### ISSUE THREAD

**Issue by kingonly** [breez/c-breez#412]
Needs to look like Breez Mobile
![Screenshot_2023-01-21-21-11-44-65_9a3a9060ca72a38f8a1fec1d0c1a640e](https://user-images.githubusercontent.com/31890660/213883256-e5f06e69-553f-49f6-bedb-a3be46079718.jpg)
![Screenshot_2023-01-21-21-10-14-59_73a31df444cba46df764485ac1a8c3ef](https://user-images.githubusercontent.com/31890660/213883257-1e64fc3b-6c74-4f3b-a19b-80a5ac82dbb7.jpg)

**Comment by ademar111190** [comment]
I did break the payment dialog widget to find eventual differences https://github.com/breez/c-breez/pull/434 https://github.com/breez/breezmobile/pull/1048

I believe what @kingonly is mentioning as a different font size is, in fact, the "title/subtitle" so I'll study how to have the same behavior with the different models we have on each project.

If you have suggestions @roeierez @erdemyerebasmaz  let me know.

**Comment by kingonly** [comment]
Your might be right. c-breez needs to have the same title subtitle logic of Breez Mobile. There's no reason for a different model.

**Comment by erdemyerebasmaz** [comment]
@ademar111190 can we close this?

**Comment by ademar111190** [comment]
We can close this issue as we have both title and subtitle now. Still, I believe we need to open a new issue to address its content; right now, both fields are duplicated; The only difference from a content perspective is for long texts where the title will trim it, and the subtitle will multiline the content.

**Comment by erdemyerebasmaz** [comment]
@ademar111190 Please go ahead open the issue you mentioned.

Closed.
