### ISSUE TITLE
Weird UI on when there's no internet connection 

### ISSUE THREAD

**Issue by kingonly** [breez/c-breez#416]
The top toolbar is fine (although we don't have it in Breez Mobile), but the rotating 3 dots are weird.
If we don't persists the balance and the payments (we should if we can), we should have text saying "Breez is waiting for an internet connection."

**Comment by roeierez** [comment]
Probably because the init_services require internet connection. Deferring that to the start method will allow the UI use the BreezServices to fetch the current state form the db.
