### ISSUE TITLE
Payment dialog title and subtitle content

### ISSUE THREAD

**Issue by ademar111190** [breez/c-breez#461]
Context: https://github.com/breez/c-breez/issues/412

Title and subtitle fields are duplicated from a content perspective; The only difference is for long texts where the title will trim it, and the subtitle will multiline the content.

**Comment by kingonly** [comment]
Please replicate the breezmobile logic. There is some duplication there in some cases as well (we have only a payment description), but not in others (when we have the payer/payee information and the description for example).
