### ISSUE TITLE
Backup prompt issues

### ISSUE THREAD

**Issue by roeierez** [breez/c-breez#478]
After testing the backup prompt I have found the following issues:
1. The warning icon is shown right on start (before sending/receiving payments).
2. On every payment there is a prompt with some invisible mask behind the dialog, giving the feeling the UI is stuck.
3. The prompt is shown on every restart.

**Comment by roeierez** [comment]
> Re 1, that's how backup warning icon behaves on new account on breezmobile.

@erdemyerebasmaz  I meant right after bootstrap, before any payment we done. This is different than breezmobile isn't it?

**Comment by erdemyerebasmaz** [comment]
> > Re 1, that's how backup warning icon behaves on new account on breezmobile.
> 
> @erdemyerebasmaz I meant right after bootstrap, before any payment we done. This is different than breezmobile isn't it?

We can display it after first payment for sure but the screenshot I attached belongs to a fresh install.

**Comment by roeierez** [comment]
I see, my mistake then. Thanks for clarifying.
