### ISSUE TITLE
Screen turns black when verifying Mnemonics

### ISSUE THREAD

**Issue by ubbabeck** [breez/c-breez#479]
With the new flow where not initially being prompted to write down and verify the  Mnemonics the screen turns black.

### Suggestion
- add suggestions when < 4 characters
- add autocomplete when user inserts 4 character

https://user-images.githubusercontent.com/36157890/218449514-67679e51-05ff-41be-91b6-05b815694f24.mp4

**Comment by kingonly** [comment]
We don't want auto complete to ensure ppl have written the phrase. Mnemonics is a technical term. We should use the term "Backup Phrase". Also the screen title is wrong (Cloud encryption key).
@erdemyerebasmaz please review the strings with me

**Comment by ubbabeck** [comment]
Agree with your reasoning with no autocomplete/ suggestions. 

One other mistake that I sometimes find myself doing when writing down the backup phrase is writing the columns downwards and not from left to write. 

Perhaps we could add some kind of colour scheme for the even/ odd numbers so that people do not accidentally write down the wrong. Though the verification page will discover this kind of wrong behaviour.

**Comment by kingonly** [comment]
@ubbabeck we have A LOT of experience with this UI from Breez mobile. We've modified it a few times in the past. We're good for now I think.

**Comment by ubbabeck** [comment]
Understand 😄  🙏
