### ISSUE TITLE
Mempool API url reset 

### ISSUE THREAD

**Issue by ubbabeck** [breez/c-breez#481]
When trying to reset the Mempool API url by pressing `reset`  it did not reset before fully closing the app and then pressing reset again.

I where able to add my local http mempool api, but not self signed https mempool api. Perhaps the issue here is that it is self signed?

Does anybody have another public available Mempool except from mempool.space we can use for testing? 

How are people expected to access their own Mempool instance?

**Comment by kingonly** [comment]
@ademar111190 please take a look
@ubbabeck ppl can run their own instance of mempool.space on a star9 or other software
