### ISSUE TITLE
QR button is disabled after fresh install 

### ISSUE THREAD

**Issue by kingonly** [breez/c-breez#489]
![Screenshot_2023-02-20-10-04-30-35_9a3a9060ca72a38f8a1fec1d0c1a640e](https://user-images.githubusercontent.com/31890660/220047721-4914e6c6-3283-46ae-b2d7-f591a0dea2c4.jpg)

Click or focus change fixes it

**Comment by roeierez** [comment]
@erdemyerebasmaz I suspect it might be an invisible dialog/mast that is shown (maybe backup prompt)?

**Comment by erdemyerebasmaz** [comment]
@roeierez No, there isn't actually a bug here. @kingonly QR button and send/receive options are disabled until account is connected to a LSP. If you click Send/Receive on startup, their options should be disabled as well.

Maybe we should grey out send & receive buttons or their text until then?
