### ISSUE TITLE
Received payment entry appears in the list after successful payment dialog

### ISSUE THREAD

**Issue by kingonly** [breez/c-breez#492]

**Comment by erdemyerebasmaz** [comment]
@kingonly We know at an earlier stage that the payment is successful and we sync node state and payment list afterwards. The delay you see is caused by the sync process.
@roeierez Do we have plans to reduce response times for node & payment list syncs?

**Comment by kingonly** [comment]
If we know the payment is successful we need to add it to list before the sync, not looking for a hack.
