### ISSUE TITLE
V icon after successful received payment should look like Breez Mobile 

### ISSUE THREAD

**Issue by kingonly** [breez/c-breez#493]
Blue, not white

**Comment by erdemyerebasmaz** [comment]
![780EEAA3-548C-435D-BF7B-05ABC9677FDB](https://user-images.githubusercontent.com/4012752/220071034-31f54710-aa37-46a4-b13d-3756be8975b7.png)
![5A0B61ED-788C-4F45-87DF-B762A26848E4](https://user-images.githubusercontent.com/4012752/220071044-52d931e8-d0a7-4a65-bfbf-64f123cf7171.png)

**Comment by erdemyerebasmaz** [comment]
@kingonly Attached comparison screenshots above, lmk what you think.

**Comment by kingonly** [comment]
Both are wrong actually. It should be blue circle with white v.

**Comment by erdemyerebasmaz** [comment]
![E71EE630-74A6-4358-BB9E-444493FFD627](https://user-images.githubusercontent.com/4012752/220119910-5f75b355-bfa8-4f3c-891f-84d6a52e15f4.png)
