### ISSUE TITLE
Lnurlp doesn't contain the URL info in the payment details dialog 

### ISSUE THREAD

**Issue by kingonly** [breez/c-breez#496]

**Comment by roeierez** [comment]
@erdemyerebasmaz status?

**Comment by kingonly** [comment]
![Screenshot_2023-03-06-13-02-12-33_9a3a9060ca72a38f8a1fec1d0c1a640e](https://user-images.githubusercontent.com/31890660/223092902-e5f03057-2ae2-45c1-b526-2303c7f2bef4.jpg)

Missing URL
