### ISSUE TITLE
Missing Payment Preimage on sent funds

### ISSUE THREAD

**Issue by kingonly** [breez/c-breez#500]
![Screenshot_2023-02-21-07-13-20-41_9a3a9060ca72a38f8a1fec1d0c1a640e](https://user-images.githubusercontent.com/31890660/220253616-ac63c52e-556e-41e7-b988-6eb15495b874.jpg)

**Comment by roeierez** [comment]
Waiting for this: https://github.com/Blockstream/greenlight/pull/194
