### ISSUE TITLE
iOS 16.1+ double prompt issue for clipboard permission

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/c-breez#521]
Clicking Paste prompts the permission dialog but it gets closed abruptly and requires a second click to give permission & use the clipboard value.

https://user-images.githubusercontent.com/4012752/223111149-7c0bf4c2-d56f-420a-a287-d8b8b20ad5ac.MOV  

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.7.6, on macOS 13.2.1 22D68 darwin-x64, locale en-TR)
    • Flutter version 3.7.6 on channel stable at /Users/erdem/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (6 days ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/erdem/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Erdem iPhone’u (mobile) • 00008030-000425810139802E • ios        • iOS 16.3.1 20D67
    • macOS (desktop)         • macos                     • darwin-x64 • macOS 13.2.1 22D68 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

@ademar111190 Could this be related to skip logic on clipboard stream?

**Comment by ademar111190** [comment]
🤔 I don't think it is related to the skip because it is skipping the data coming from the preferences. Can you attach the logs?  I believe you are running on a simulator, right? which iOS version are you using on it? Apple has changed the clipboard access logic a few times, so maybe it is version specific.

**Comment by erdemyerebasmaz** [comment]
> 🤔 I don't think it is related to the skip because it is skipping the data coming from the preferences. Can you attach the logs? I believe you are running on a simulator, right? which iOS version are you using on it? Apple has changed the clipboard access logic a few times, so maybe it is version specific.

I'm on a physical device, iPhone 11 with 16.3.1 version.

_Will attach logs._

**Comment by erdemyerebasmaz** [comment]
@ademar111190 

> [Pasteboard] ...requesting item failed with error: Error Domain=PBErrorDomain Code=13 "Operation not authorized." UserInfo={NSLocalizedDescription=Operation not authorized.}

More information [here](https://github.com/flutter/flutter/issues/121446)

**Comment by roeierez** [comment]
@erdemyerebasmaz can we close this?

**Comment by erdemyerebasmaz** [comment]
> @erdemyerebasmaz can we close this?

@roeierez not yet, it depends on the issue referenced here: 
https://github.com/breez/c-breez/issues/521#issuecomment-1457681237

**Comment by erdemyerebasmaz** [comment]
@roeierez I've changed my mind, this can be closed as it's only reproducible between copying pasting between another Apple device([Handoff](https://support.apple.com/guide/mac-help/hand-off-between-devices-mchl732d3c0a/mac)).
