### ISSUE TITLE
Match Breezmobile UI for Success Action Dialog

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/c-breez#524]

**Comment by kingonly** [comment]
![Screenshot_2023-03-07-08-24-00-18_9a3a9060ca72a38f8a1fec1d0c1a640e](https://user-images.githubusercontent.com/31890660/223338365-65903e2e-c390-4273-bcf6-5642ba9c5819.jpg)
![Screenshot_2023-03-07-08-21-16-43_73a31df444cba46df764485ac1a8c3ef](https://user-images.githubusercontent.com/31890660/223338367-f91a84ee-1f5b-4222-8a7c-df286147d40a.jpg)
