### ISSUE TITLE
Closed Channel Information is not showing correctly 

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#536]
![Screenshot 2023-03-14 113940](https://user-images.githubusercontent.com/127208515/224967612-426c403d-4f8d-4dde-9f17-060bf2ca48c6.jpg)

**Comment by ubbabeck** [comment]
Depends on https://github.com/breez/breez-sdk/issues/484

**Comment by ubbabeck** [comment]
Moved from this milestone as it will not be included in the next release of the sdk.

**Comment by Nackoo2000** [comment]
The channel was closed 4 hours ago and the balance screen shows a moment ago. 
The sats that were in the channel do not appear anywhere.
There is no hash for the closing transaction ID.

![image](https://github.com/breez/c-breez/assets/127208515/e607a786-98b3-4152-b3d1-dd98c4945c86)
![image](https://github.com/breez/c-breez/assets/127208515/82e8c02f-7ebc-437f-a686-7eebbd3ea4a6)
