### ISSUE TITLE
Blank screen when starting the app

### ISSUE THREAD

**Issue by literalEval** [breez/c-breez#546]
**Info**

I have setup every pre-requisite correctly, i.e., the `breez-sdk` directory is a sibling of `c-breez` directory. The build runs fine and the app starts, but there is nothing on the screen (just a blank white screen). There are no flutter logs, so can't say what's wrong. Will debug more and try to find the exact problem.

Do I need to run a Greenlight/Breez/lnd node just to see something on the screen? If yes, I think this can be made an error and shown to the user just like `breezmobile` shows `No connection detected`

**Comment by kingonly** [comment]
This isn't the right forum, you don't have the proper build configuration. You should just use the code a reference. If selected, we'll set you up sdk access.

**Comment by literalEval** [comment]
Understood :)
