### ISSUE TITLE
LNURL - Pay on Android - Avatar and Title are missing

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#551]
1. Open an LNURL application - lightning.gift
2. Scan the QR code with Breez Cloud 
3. Enter the amount of sats 
4. Click Approve

![image](https://user-images.githubusercontent.com/127208515/233847379-da040358-d5c8-4730-954c-7127ff119aa1.png)

**Comment by ubbabeck** [comment]
This was fixed by this pr https://github.com/breez/c-breez/pull/580.
![metadata](https://github.com/breez/c-breez/assets/36157890/fd6d2992-80f3-4ffa-85c6-0a214a6b9ead)
