### ISSUE TITLE
flutter run fails on x86_64 emulator

### ISSUE THREAD

**Issue by JssDWt** [breez/c-breez#553]
SDK version: https://github.com/breez/breez-sdk/commit/4db7c576807ed974512b56451b9bd03e360436ee
c-breez version: https://github.com/breez/c-breez/commit/b58026f5d827752f126b01b668463fc3e50a8416
OS: macOS Ventura 13.3.1
clang version:
```
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
rustc version: 1.69.0
NDK version: 25.2.9519653
Emulator properties:
```
Properties
avd.ini.displayname              Pixel XL API 33
avd.ini.encoding                 UTF-8
AvdId                            Pixel_XL_API_33
disk.dataPartition.size          6442450944
fastboot.chosenSnapshotFile
fastboot.forceChosenSnapshotBoot no
fastboot.forceColdBoot           no
fastboot.forceFastBoot           yes
hw.accelerometer                 yes
hw.arc                           false
hw.audioInput                    yes
hw.battery                       yes
hw.camera.back                   virtualscene
hw.camera.front                  emulated
hw.cpu.ncore                     4
hw.device.hash2                  MD5:f78477654d5471c3d7f705251d14e72f
hw.device.manufacturer           Google
hw.device.name                   pixel_xl
hw.dPad                          no
hw.gps                           yes
hw.gpu.enabled                   yes
hw.gpu.mode                      auto
hw.initialOrientation            Portrait
hw.keyboard                      yes
hw.lcd.density                   560
hw.lcd.height                    2560
hw.lcd.width                     1440
hw.mainKeys                      no
hw.ramSize                       1536
hw.sdCard                        yes
hw.sensors.orientation           yes
hw.sensors.proximity             yes
hw.trackBall                     no
image.androidVersion.api         33
image.sysdir.1                   system-images/android-33/google_apis/x86_64/
PlayStore.enabled                false
runtime.network.latency          none
runtime.network.speed            full
showDeviceFrame                  yes
skin.dynamic                     yes
tag.display                      Google APIs
tag.id                           google_apis
vm.heapSize                      384

```

Output
```
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...        2.641ms
I/flutter ( 4514): log list indexes: [1]
I/flutter ( 4514): Logfile is /data/user/0/com.cBreez.client/app_flutter/logs/c_breez.1.log
E/Main    ( 4514): FlutterError: Invalid argument(s): Failed to load dynamic library 'libbreez_sdk_core.so': dlopen failed: cannot locate symbol "__extenddftf2" referenced by "/data/app/~~UcBFNlatEEBdCCcwgFiyIw==/com.cBreez.client-Sa2PlTMqW3zf_nxnw3Cxjw==/lib/x86_64/libbreez_sdk_core.so"...
E/Main    ( 4514): Invalid argument(s): Failed to load dynamic library 'libbreez_sdk_core.so': dlopen failed: cannot locate symbol "__extenddftf2" referenced by "/data/app/~~UcBFNlatEEBdCCcwgFiyIw==/com.cBreez.client-Sa2PlTMqW3zf_nxnw3Cxjw==/lib/x86_64/libbreez_sdk_core.so"... 
E/Main    ( 4514):      #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/Main    ( 4514):      #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/Main    ( 4514):      #2      getNativeToolkit (package:breez_sdk/native_toolkit.dart:17:51)
E/Main    ( 4514):      #3      new BreezBridge (package:breez_sdk/breez_bridge.dart:10:22)
E/Main    ( 4514):      #4      ServiceInjector.breezLib (package:c_breez/services/injector.dart:53:48)
E/Main    ( 4514):      #5      main.<anonymous closure> (package:c_breez/main.dart:45:31)
E/Main    ( 4514):      <asynchronous suspension>
E/Main    ( 4514):
```

@erdemyerebasmaz found a related issue here https://github.com/mozilla/rust-android-gradle/issues/105#issuecomment-1481931362

**Comment by erdemyerebasmaz** [comment]
I was able to reproduce on pretty much the same environment. The x86_64 emulator I used had an old version of c-breez installed that was functional.

**Comment by ok300** [comment]
I had the exact same error when trying to run the React Native SDK example on an Android x86_64 image:

```
cannot locate symbol "__extendsftf2"
```

After some research, it turns out the issue doesn't exist on ARM (running the app on a connected physical Android) or just x86 emulator images.

Try to use an x86 (instead of x86_64) image in your Android Studio, chances are that will fix this problem.

cc @dangeross @ademar111190

**Comment by dangeross** [comment]
Could it be related to this issue: 

[Several configure&make packages give binaries with cannot locate symbol "__extendsftf2"](https://github.com/termux/termux-packages/issues/8029#issuecomment-1369150244)

Seems it could be related to the NDK version and maybe fixable with this workaround when building the library:
```
RUSTFLAGS+=" -C link-arg=$($CC -print-libgcc-file-name)" 
```

**Comment by ok300** [comment]
Same behavior for me on x86_64, even with the extra `RUSTFLAGS`.

**Comment by ademar111190** [comment]
Just confirmed the same behavior on an Android x86_64 emulator in a Linux host.

**Comment by yukibtc** [comment]
Try this workaround (must be added in build.rs)

https://github.com/smartvaults/smartvaults/blob/master/bindings/smartvaults-sdk-ffi/build.rs

**Comment by JssDWt** [comment]
@yukibtc Thanks a lot! Just tried your code and it works for us too. Made a PR here https://github.com/breez/breez-sdk/pull/479
Question: Do I need to include the copyright notice there?

**Comment by yukibtc** [comment]
Nice!

> Question: Do I need to include the copyright notice there?

No

**Comment by JssDWt** [comment]
Fixed by https://github.com/breez/breez-sdk/pull/480 and https://github.com/breez/breez-sdk/pull/479

**Comment by JssDWt** [comment]
For people stumbling on this issue for a solution, I recommend checking our current solution which links the right clang path for x86_64 builds [here](https://github.com/breez/breez-sdk/blob/d658f85c7c349bd7ed96c05c3d008b7b75e6273a/libs/sdk-bindings/build.rs#L6-L33)

Probably even better to look at the latest version on the main branch in case more updates will be added later: https://github.com/breez/breez-sdk/blob/main/libs/sdk-bindings/build.rs
