### ISSUE TITLE
Bad UI - Missing fee in payments screen

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#568]
1. Install Breez Cloud
2. Click Let's Breez
3. Click Receive via BTC Address
4. Sent 55000 sats
5. Received 50000 sats and 5000 sats fee for creating the channel is missing in the payments screen.

![image](https://github.com/breez/c-breez/assets/127208515/012ba131-f154-4ce6-8e6c-e1c2e2ebe0c0)

**Comment by Nackoo2000** [comment]
The same applies for receiving via invoice. 

![image](https://github.com/breez/c-breez/assets/127208515/080d085a-a8f3-4b85-9ca5-dc9bbdd5f80f)

**Comment by roeierez** [comment]
No, we should show the fee was paid for the channel (5000 sats in this case).

**Comment by Nackoo2000** [comment]
Yes only when there is a new channel creation the fee is missing.

**Comment by ademar111190** [comment]
I see, so it is a sdk issue, is it possible to move this issue to the sdk repo @roeierez ?
