### ISSUE TITLE
LNURL withdraw problem

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#569]
1. Created Lightning gift URL 100 sats - https://lightning.gifts/
2. Scan the QR code for withdrawing the gift

It shows NO_ROUTE and the sats cant be retrieved because the QR is not available anymore.

![image](https://github.com/breez/c-breez/assets/127208515/8585f0b6-7b4f-4226-8392-a57827dd97fe)
![image](https://github.com/breez/c-breez/assets/127208515/cf1c641d-626e-418b-b8b2-03dd311f2edf)

**Comment by kingonly** [comment]
Did it work in Breez mobile?

**Comment by kingonly** [comment]
So this is an issue with lightning.gifts and not c-breez.
