### ISSUE TITLE
LNURL withdraw error

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#571]
When withdrawing the funds arrive but this message is displayed:

![image](https://github.com/breez/c-breez/assets/127208515/61d2b14a-bb9b-4956-8117-4926c6e6cce4)

**Comment by roeierez** [comment]
please attach the logs.

**Comment by ademar111190** [comment]
@Nackoo2000 could you add more details? Perhaps the logs too as @roeierez asked? I couldn't replicate this issue.

**Comment by Nackoo2000** [comment]
I use Fountain app to create an LNURL
Scan it with CBreez or copy and paste the invoice.

Sorry for the delay of the logs.

[c-breez.logs (4).zip](https://github.com/breez/c-breez/files/11759987/c-breez.logs.4.zip)
