### ISSUE TITLE
Bad UX - hard to scan a QR code when in night mode

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#576]
Trying to scan a QR code on my phone from my laptop to transfer to Alby is hard and sometimes it does not even detect the QR code when Breez is in night mode. 

When I switch to light mode there is no problem.

![image](https://github.com/breez/c-breez/assets/127208515/16adacf8-05b2-44e6-bfb4-bedcba7b5cf9)

**Comment by kingonly** [comment]
Again, Breez mobile should be used a reference. This is more of a camera issue.
