### ISSUE TITLE
Payments to Alby inconsistent

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#577]
When I am trying to pay to Alby in the browser extension it is very inconsistent and about 50% of the payments fail.

Check the last 3 payments here this happened and 2 were successful.
![image](https://github.com/breez/c-breez/assets/127208515/b8597c91-b1dc-4fec-a132-f4d0e70c0d06)
[c-breez.logs.zip](https://github.com/breez/c-breez/files/11767197/c-breez.logs.zip)

**Comment by kingonly** [comment]
This is a duplicate bug. Add the logs to the previous one and work with Roei to report the issue to Christian.

**Comment by Nackoo2000** [comment]
@kingonly  Is it the same as the WoS one?

**Comment by kingonly** [comment]
See the error message. Same as the lnurl bug you opened which isn't lnurl. WoS is probably the same.
