### ISSUE TITLE
logs should be in UTC time

### ISSUE THREAD

**Issue by JssDWt** [breez/c-breez#587]
Currently the times in the logs are printed in local time, It would save us quite some headaches if we log in UTC time I think.

**Comment by erdemyerebasmaz** [comment]
This is currently not supported by the logging library we're using.
Depends on
- https://github.com/magillus/flutter-fimber/issues/129

**Comment by ademar111190** [comment]
Another reason to move for logging, I'll take a look at this issue.

**Comment by ademar111190** [comment]
Added this commit https://github.com/breez/c-breez/pull/657/commits/b4336d957850786c59e8a866022ee1d6176bd7fe to the log library change and as soon as it merges we get UTC time in iso format
