### ISSUE TITLE
Sending to Breez mobile invoice failing

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#590]
1. Created an invoice for 500 sats on breez mobile (iOS device)
2. Scanned the QR with CBreez (Android)
3. Waited for ~90sec and displayed payment failed 

[c-breez.logs.zip](https://github.com/breez/c-breez/files/11917472/c-breez.logs.zip)

**Comment by kingonly** [comment]
Report this issue in the c-breez channel

**Comment by kingonly** [comment]
You're not testing on the same device, right?

**Comment by kingonly** [comment]
Works for me

**Comment by kingonly** [comment]
Please retest

**Comment by Nackoo2000** [comment]
Retested on iOS and Android everything works.
