### ISSUE TITLE
Pasting to CBreez from WoS - CBreez is closed before pasting (iOS)

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#594]
1. Generating an invoice in WoS
2. Copy the invoice
3. Start and open CBreez
4. Click Allow Pasting

It does not paste the invoice.

https://github.com/breez/c-breez/assets/127208515/a220eb24-9df3-4d3e-b70c-0fdf2d581ad8

**Comment by kingonly** [comment]
The title and the steps don't reflect the issue. "When Breez is closed"

**Comment by Nackoo2000** [comment]
Same with a Lightning address

https://github.com/breez/c-breez/assets/127208515/27fa718a-939b-4dd7-a49d-089d94970e73

**Comment by kingonly** [comment]
You mean lnurl, not lightning address (WoS UI is confusing). The QR is lnurlp.

**Comment by ubbabeck** [comment]
This has been solved with https://github.com/breez/c-breez/pull/593.

**Comment by kingonly** [comment]
@Nackoo2000 please verify
