### ISSUE TITLE
Balance screen not updating

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#604]
The last two payments appear in the history but the balance did not change.
![image](https://github.com/breez/c-breez/assets/127208515/a75e4143-8aee-4433-8533-5822b890efcf)
[c-breez.logs (14).zip](https://github.com/breez/c-breez/files/12063602/c-breez.logs.14.zip)

**Comment by Nackoo2000** [comment]
After closing CBreez and reopen it then it updated the balance:
![image](https://github.com/breez/c-breez/assets/127208515/f483838b-b62e-4041-8a66-e24666baf811)

**Comment by erdemyerebasmaz** [comment]
Depends on
- https://github.com/breez/breez-sdk/pull/341

**Comment by ubbabeck** [comment]
This issue has been resolved. Balance updated both when receiving and sending, closing.
