### ISSUE TITLE
Paste invoice or ID - Multiple pasting

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#609]
1. Copy an invoice from another wallet (or LNURL from WoS)
2. Open CBreez
3. Cancel the autopasting
4. Click send
5. Click paste invoice or ID

It pastes the same invoice from the clipboard multiple times.

It should paste the invoice/LNURL only one time from the clipboard.

https://github.com/breez/c-breez/assets/127208515/d6a72421-3d4d-4581-8a35-4f94918f715c

**Comment by kingonly** [comment]
This is the behavior in Breez mobile, correct?

**Comment by Nackoo2000** [comment]
No in Breez mobile it is not the same behavior.
Here is a comparison video if my description was not enough.

https://github.com/breez/c-breez/assets/127208515/36f37eb3-16cf-48bf-8744-8c62b06b66bf

**Comment by kingonly** [comment]
Your description doesn't include the expected result

**Comment by ubbabeck** [comment]
The difference is that if we in C-breez have an invoice, lnurl, nodeID etc in the clipboard when pressing paste ID or invoice we do not display the Payee dialog but rahter the corresponding page or dialog. This behaviour removes the step of pasting manually like we do in Breezmobile. @erdemyerebasmaz feel free to clarify.

**Comment by kingonly** [comment]
The behavior should be like in Breez mobile. The corresponding dialog should be displayed at the first time, but not after cancelling.
