### ISSUE TITLE
[Visual feedback] Dynamic Fee UI when LSP does not support opening channels

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/c-breez#618]
Dynamic fees PR introduces new messages & UI's when the connected LSP temporarily does not support opening channels.

### When a user tries to create an invoice with an amount larger than their inbound liquidity:

`"Insufficient inbound liquidity (${inboundLiquidity})"`

<img src="https://github.com/breez/c-breez/assets/4012752/2e8b7da5-b9e1-46b2-835e-9f426642f231" width="33%" />

I suggest we
- Display a warning box and inform that the LSP does not support opening channels temporarily,
- Replace "Receive up to:" amount with inbound liquidity if it's less than maximum depositable amount,
- If inbound liquidity is 0, disable creating an invoice until connected LSP supports opening channels

for this case.

We should also allow users to pick another LSP if  current LSP does not support opening channels(_considering the LSP list has more than one LSP_). 

---

### When a user tries to create a swap address:

A warning box, at the center of where the QR image would be, with the unedited error message from the SDK is displayed.

<img src="https://github.com/breez/c-breez/assets/4012752/2709b5f4-0e56-48b6-9a3f-a7d8b83ae253" width="33%" />

A more user friendly & translatable message is recommended and the UI could use another polish to better convey that there was an error in generating a swap address.

**Comment by kingonly** [comment]
@erdemyerebasmaz your suggestions in the bullets make sense.
Put LSP selection aside. It's not relevant for this PR.

Re the sentence: in the world with Chat GPT, I expect better. Go through Chat GPT and send me the sentence for approval afterwards.
