### ISSUE TITLE
Missing icons on the Receive and Send menus

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#642]
Reproduce:
 - Kill the app
 - Open the app
 - Click on "Receive" or "Send"
 
 Result - The menus appear with a big lag and the icons in the options do not appear
 
https://github.com/breez/c-breez/assets/127208515/ba94a7c7-dee9-4bfd-a1da-76faeb8a11a6

NOT Reproducing:
 - Kill the app
 - Open the app
 - Wait ~30 sec
 - Click on "Receive" or "Send"
 
 Result: There is no lag and icons appear.

**Comment by Nackoo2000** [comment]
The lagging happens not only when killing the app

It happens on any screen that the app comes to the front from the background. The buttons do not work for the first ~20 sec.

**Comment by ubbabeck** [comment]
Not able to reproduce on my iPhone. 
@Nackoo2000 What iPhone are you using to test?

It might take some time for apps to initialise on older devices.

**Comment by Nackoo2000** [comment]
This happens on iPhone 13 and iPhoneSE for me.
The problem is also that if I wake up the app there is a lag in the pressing of any button/menu not just the missing icons.
After I wait ~30 seconds the app is not lagging anymore.

**Comment by ubbabeck** [comment]
it might be tied to network constrains and not device constrains. 

the buttons might depend on lsp connection, I think this can be deferred and rather display an error if there is conneciton issues.
