### ISSUE TITLE
Key from the keyboard for fiat denomination not working

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#644]
The button for decimal point in fiat denomination does not work.

![image](https://github.com/breez/c-breez/assets/127208515/c24e75dc-2fd4-47c9-997d-c7342f66421c)

**Comment by Nackoo2000** [comment]
@ubbabeck  This is still not working for me on iOS 6100.1 version

**Comment by ubbabeck** [comment]
works on my testflight 6100.1. what are your steps to reproduce?

https://github.com/breez/c-breez/assets/36157890/2019cb03-339e-4829-a474-d77bd2074054

**Comment by Nackoo2000** [comment]
My bad I retested and everything works fine.
