### ISSUE TITLE
Verifying the seed phrase

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#647]
When installing Breez Cloud and creating a new node I am not asked to verify my seed phrase.
There is no warning icon about it showing up.

**Comment by kingonly** [comment]
Also after a payment? Vanilla node w/o payments isn't important.

**Comment by Nackoo2000** [comment]
Yes even after payments. Tested with up to 30K in the wallet and there is no pop-up.

**Comment by kingonly** [comment]
But is there a warning?

**Comment by kingonly** [comment]
See: https://github.com/breez/c-breez/issues/395

**Comment by Nackoo2000** [comment]
I do not see a warning. Am I missing it somewhere:

https://github.com/breez/c-breez/assets/127208515/a8795b2e-3644-404e-9372-009b9ebe2080

**Comment by kingonly** [comment]
This is a regression for sure
