### ISSUE TITLE
LNURL - Withdraw error message

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#655]
The LNURL-Withdraw is working but this message is displayed.
In the pictures are the tests from lightning.gifts 101 sats and opentip.io 14 sats

![image](https://github.com/breez/c-breez/assets/127208515/2f10329e-2b76-43b8-87fd-2448e1d705f7)
![image](https://github.com/breez/c-breez/assets/127208515/516c2096-6385-4fab-b7e6-84a365ed6006)

[c-breez.logs (11).zip](https://github.com/breez/c-breez/files/12818919/c-breez.logs.11.zip)

**Comment by ubbabeck** [comment]
This is the error message we receive from the lnurlw service and is most likely tied to how they resolved failed sending. 

@Nackoo2000 does this happen when you scan the lnulw qr or when you press `Redeem`?

**Comment by Nackoo2000** [comment]
When scanning
