### ISSUE TITLE
GetInfo command 

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#656]
Users can't easily find their node ID without the GetInfo command in the Developers screen

![image](https://github.com/breez/c-breez/assets/127208515/c4beb62f-f6a2-4793-8f17-10ff625475d4)

**Comment by kingonly** [comment]
So? What's the difference between this and Breez mobile?

**Comment by kingonly** [comment]
You mean non of these commands spits the node id?

**Comment by Nackoo2000** [comment]
Yes none of them spit out the node ID + The Breez mobile is so much more but not sure which are applicable yet in BreezC

https://github.com/breez/c-breez/assets/127208515/e8aa5814-3f1f-435e-a276-9791efb86152
