### ISSUE TITLE
Failed receive via BTC Address and warning pop up

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#661]
I sent an on-chain transaction from BreezM to BreezC - 
https://github.com/breez/c-breez/assets/127208515/b9697617-ddf1-4cb2-9a9c-3359d283a1cc

The transaction was sent successfully from BreezM
And it was confirmed - https://mempool.space/tx/59c1b6dd3293c04f8aae34ab71a15718e3fd9d0e6c07c8153004c159f6c99594

The balance did not appear in BreezC and when @roeierez  and @yaslama fixed the underlying issue the swapper node was not able to pay.

Now in BreezC I can receive another payment via BTC Address but the 55555sats was supposed to come as a warning icon and for me to withdraw to another address.
The warning icon never appeared.
Here are the logs.
[c-breez.logs (10).zip](https://github.com/breez/c-breez/files/12841148/c-breez.logs.10.zip)

**Comment by roeierez** [comment]
@Nackoo2000 The logs you attached are from the 4/10 which is 5 days ago. From the logs I see that the sdk detected the funds are confirmed but we are still not passed the timeout that is required for refund.
Please open the app again and see if you see the refund icon. If not, please attach new updated logs.

**Comment by Nackoo2000** [comment]
No refund icon yet here are the proper logs:
[c-breez.logs (12).zip](https://github.com/breez/c-breez/files/12843912/c-breez.logs.12.zip)
