### ISSUE TITLE
Scan button issue

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#671]
When scanning an old format within the scan from "Send to BTC Address" it works

When scanning a QR code with the scan button on the bottom of the balance screen nothing happens.

https://github.com/breez/c-breez/assets/127208515/515904b5-640e-451f-9ad3-cbd1709d680f

**Comment by ademar111190** [comment]
@Nackoo2000 can I ask you three things?
- The logs
- Check if it is working on Android
- Check the build you use (My fix was merged late yesterday, maybe you tested in version without the fix)

**Comment by Nackoo2000** [comment]
[c-breez.logs (14).zip](https://github.com/breez/c-breez/files/12872028/c-breez.logs.14.zip)

Android is working

I use the build from an hour ago

**Comment by ademar111190** [comment]
@Nackoo2000 I read the logs here; I'm not sure why, but the build you are using does not have my changes yet.

**Comment by Nackoo2000** [comment]
@ademar111190 tested again on the new build and it works fine so I am closing the issue.
