### ISSUE TITLE
unexpected funds

### ISSUE THREAD

**Issue by ubbabeck** [breez/c-breez#676]
When the internal wallet has a confirmed on-chain tx we display unxepected funds warning, but the wallet does not check if the funds are reserved until block height > now so when the user tries to spend the funds they receive an error. 

Solution: show warning dialog with info about the reserved utxos if the blockheight isn't reached yet.

**Comment by kingonly** [comment]
@ubbabeck what's the use case? What's Breez mobile behavior? Why are the funds reserved?

**Comment by roeierez** [comment]
Funds are reserved in case the user has already called sweep. In that case core lightning reserves the funds.
I think a better course of action would be to unreserve the funds before broadcasting the sweep transaction (https://docs.corelightning.org/reference/lightning-unreserveinputs).
This way the user has an option to replace a low fee already broadcasted transaction with a new one.

**Comment by ubbabeck** [comment]
Got it, thanks for clarifying @roeierez.

**Comment by ubbabeck** [comment]
Created issue in breez-sdk https://github.com/breez/breez-sdk/issues/531. Closing..
