### ISSUE TITLE
lnurlp doesn't work if the app is closed 

### ISSUE THREAD

**Issue by kingonly** [breez/c-breez#678]
1. Make sure the app is closed
2. Copy lnurlp link from WoS
3. Open the app

Nothing happens

**Comment by ademar111190** [comment]
Didn't manage to reproduce it locally.

@kingonly can you share the device specs you are using and the logs?

**Comment by ubbabeck** [comment]
Not able to reproduce on iOS using CBreez 6106.1

**Comment by ademar111190** [comment]
Thanks for testing @ubbabeck 
What ios version did you test on? (that is relevant because clipboard API has changed a lot between ios versions)

**Comment by kingonly** [comment]
Android OnePlus 8


https://github.com/breez/c-breez/assets/31890660/42561d15-cf7a-47ef-865a-eb009b5af762

**Comment by ademar111190** [comment]
Is it Android 13 @kingonly ?
Do you mind sharing the logs?

**Comment by ubbabeck** [comment]
> Thanks for testing @ubbabeck 
> 
> What ios version did you test on? (that is relevant because clipboard API has changed a lot between ios versions)

iOS 16.6.1

**Comment by roeierez** [comment]
@ademar111190 is this fixed by the related PR?

**Comment by ademar111190** [comment]
@roeierez  I was not able to reproduce the bug; that fix was my best effort given Roy's logs.
So I kindly ask @kingonly to test it and tell us if it is working now.

**Comment by ubbabeck** [comment]
@ademar111190 i have forwarded some logs which are failing to you.

**Comment by ademar111190** [comment]
@ubbabeck are you talking about https://github.com/breez/c-breez/issues/694 right?
I don't think they are related; working on that issue as well.
