### ISSUE TITLE
No expiration time for invoice

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#679]
When I try to send an invoice and the payment is pending there is no expiration date for the invoice.
Right now I have an invoice pending for 20 hours and counting.
![image](https://github.com/breez/c-breez/assets/127208515/cd54c07c-5013-4ee2-819f-7356c37df6c2)
![image](https://github.com/breez/c-breez/assets/127208515/25577048-4911-45ad-a21c-0fca3e0c8aee)

**Comment by erdemyerebasmaz** [comment]
@ok300 is expiration timestamp information available for pending transactions on the SDK?

**Comment by ok300** [comment]
Yes, on `receive_payment` we always set the invoice `expiry`, even if the caller passed a value or not.

**Comment by erdemyerebasmaz** [comment]
> Yes, on `receive_payment` we always set the invoice `expiry`, even if the caller passed a value or not.

This seems to be a sent invoice using `sendPayment`

**Comment by ok300** [comment]
AFAIK all invoices have an `expiry` field, and if a payment is sent, then the invoice is known and the expiry field can be read.

How is the app getting the expiration date? Using what service method or field?

**Comment by ok300** [comment]
@roeierez would it make sense to add a

```rust
pub expiry: Option<u64>
```
to `Payment` or `LnPaymentDetails`?

**Comment by roeierez** [comment]
The expiration here refers to the block the htlc expires. It is for pending htlcs.
Last time I checked greenlight didn't return the correct htlcs for pending payments (the array was empty).
Worth checking that again and if the htlc arrays is returned then we can take the block number from there and add it to the pending payment.
