### ISSUE TITLE
Remove "Fine" level logs

### ISSUE THREAD

**Issue by roeierez** [breez/c-breez#681]
CurrentlyI see in c-breez lots of verbose logs: 

[BreezSdk] {FINE} (2023-10-12T06:08:41.329401Z) : poll
[BreezSdk] {FINE} (2023-10-12T06:08:41.329607Z) : attempting to decode a frame
[BreezSdk] {FINE} (2023-10-12T06:08:41.329668Z) : <- FramedRead::poll_next;
[BreezSdk] {FINE} (2023-10-12T06:08:41.329705Z) : -- FramedRead::poll_next;
[BreezSdk] {FINE} (2023-10-12T06:08:41.329748Z) : try_reclaim_frame;

Let's filter them.

**Comment by ademar111190** [comment]
@roeierez I'm thinking about the best approach between development flow and debugging, what do you think about the following approach:

- Keeping all logs at the log file level
  - That will be useful for bug reports
  - I can improve the log filter script to allow filtering by tag and level
- Skip Fine logs on Logcat/Xcode as they usually aren't useful when working with the app.

That is what the changes look like, let me know your thoughts:
https://github.com/breez/c-breez/pull/683

**Comment by roeierez** [comment]
Also we should leave debug level for now as we get useful info about the node logs and the signer
