### ISSUE TITLE
lnurlp and lnurlw not converted when btc denomination is selected.

### ISSUE THREAD

**Issue by ubbabeck** [breez/c-breez#689]

**Comment by Nackoo2000** [comment]
@ubbabeck  please provide some more context or info on how to test it.

**Comment by ubbabeck** [comment]
1. Go go home page
2. See that `btc` is selected as bitcoin denomination
3. Scan lnurlp /w from here https://lnurl.fiatjaf.com/ or other lnurlp / w service.
4. See that correct amount is correctly displayed in selected denomination
5. Do the same with sat.
