### ISSUE TITLE
Android UI stuck on pasting a LNURL to Breez Cloud

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#694]
The issue happened when trying to paste from clipboard to Breez Cloud - Breez was closed

This was on Android 8.0.0

I sent 2 sats to this wallet from WoS after the "stuck" happened. The payment went through the WoS but never appeared in BreezC
Also, the side menu and the button are working but when trying to send it does not load any sending screen for any of the methods.

![image](https://github.com/breez/c-breez/assets/127208515/19cf0365-bd18-41b1-a83a-ee8c33e23a59)
[c-breez.logs (16).zip](https://github.com/breez/c-breez/files/13114626/c-breez.logs.16.zip)

**Comment by Nackoo2000** [comment]
@ademar111190  I got unstuck by upgrading my Xperia system to the latest version but still Android 8.0.0
I copied an @ LNURL from WoS and opened BreezC - the result was the same. I will record it tomorrow.
[c-breez.logs (17).zip](https://github.com/breez/c-breez/files/13126208/c-breez.logs.17.zip)

**Comment by ademar111190** [comment]
thanks @Nackoo2000 waiting for the video

**Comment by ademar111190** [comment]
Thanks for the recordings and logs @Nackoo2000 with your help I've found the root of the issue;
I hope once my fix is merged you can have the app working properly again.
