### ISSUE TITLE
contiguous logs 

### ISSUE THREAD

**Issue by ubbabeck** [breez/c-breez#723]
The logs in c-breez seems to create a new file per session. I would be easier to debug users logs if the logs were bigger contiguous files.

**Comment by ademar111190** [comment]
@ubbabeck we did in the past with the previous library; with the current library, there is no mechanism to do that.

Check the Drawback section at https://github.com/breez/c-breez/pull/657

**Comment by ubbabeck** [comment]
I take back my statement, it is useful with per session logs when debugging. Closing
