### ISSUE TITLE
Add Reporting a Payment Failure

### ISSUE THREAD

**Issue by ubbabeck** [breez/c-breez#730]
ref https://github.com/breez/breez-sdk/pull/627

**Comment by kingonly** [comment]
@ademar111190 please prioritize this

**Comment by ademar111190** [comment]
I’ve studied the breez mobile behavior and that is what I saw:

Once an error of PaymentError type happens, the report flow starts:

1. A boolean flag is checked `ignoreGlobalFeedback`
    - If such flag is true; the whole report flow is dismissed
 2. Then the error message and trace report are checked
    - If the error message contains `rpc error` or the trace report is null or empty the error is considered a `validation error`
3. If it is a validation error and the error message contains `payment is in transition`, the report flow is dismissed
4. The snack bar is shown with the error message and an ok button to dismiss it
    - it is dismissed automatically after 8 seconds
5. If it is not a validation error an additional flow starts:
6. If the user has set the Bug Report Behavior to `ignore`, the flow ends
7. If the user has set the Bug Report Behavior to `send report`, the error is sent to breez
8. If the user has not changed the Bug Report Behavior yet; a dialog opens where the user can:
    - Set the `Don’t ask me again` option; i.e.; change the Bug Report Behavior to ignore if the user taps “NO” or to “send report” if the user taps “Yes”
    - User taps yes we send the report
    - User taps no we don’t send report
    
If you see some flaw; or something missing please let me know cc @roeierez @kingonly 

I'll check how to apply this logic on c-breez, in special ignoreGlobalFeedback, validation error and error messages as the data models are different on c-breez; the other stuff; user preference and UI/UX is quite straightforward. 

I'm attaching two videos for reference of how the report flow looks like on breez mobile


|With prompt|No prompt|
|---|---|
|<video src="https://github.com/breez/c-breez/assets/1225438/7f0f7a1a-3403-475d-8d67-544dce59c3e3" />|<video src="https://github.com/breez/c-breez/assets/1225438/95abf8d8-fce7-4894-a6cc-f9df350b9290" />|
