### ISSUE TITLE
Problem with closed channel funds

### ISSUE THREAD

**Issue by kingonly** [breez/c-breez#738]
I have two issues:
* My channel was closed, but funds were not swept to the local on-chain wallet.
* Closed Channel entry isn't in pending.

**Comment by ubbabeck** [comment]
Reached out to you on dm.

**Comment by kingonly** [comment]
@Nackoo2000 I can't reproduce this. Please test force close flow (ask Akiba to force close) and if everyone works as expected, close this bug please.
