### ISSUE TITLE
Preferences sub menus bug

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#740]
1. Open Developers screen
2. Click back from Developers screen
3. Click on any sub-menus (Fiat Currencies, Network, Security&Backup, Lightning Fees, Developers) I can't enter unless restarting the app

https://github.com/breez/c-breez/assets/127208515/7c6b242c-80d4-41ab-baea-ece77936b0d7

**Comment by ademar111190** [comment]
@Nackoo2000 can you share your logs and confirm it is still happening?

**Comment by erdemyerebasmaz** [comment]
We might want to revert [Deprecate just-in-time navigation pop APIs for Android Predictive Back](https://github.com/breez/c-breez/pull/719/commits/9527268164063bfadd18795b6973cb7e73898faf), there's too much variance in behavior from device to device.
