### ISSUE TITLE
Fonts too small

### ISSUE THREAD

**Issue by kingonly** [breez/c-breez#746]
First is Breez mobile, second is c-breez, see the send/receive bar on the bottom. 

![Screenshot_20231224-110945](https://github.com/breez/c-breez/assets/31890660/5f5a9398-db2d-4015-8c0e-3e2df48a220c)
![Screenshot_20231224-110948](https://github.com/breez/c-breez/assets/31890660/78ccf614-f754-4447-ac8c-a016ed15fb42)

**Comment by ademar111190** [comment]
I studied both codebases and now I comprehend the reasons for their differences and have findings to share with you @kingonly  I didn’t expect these findings to be honest, so I’m interested to know your thoughts.

c-breez was recently changed to align with the latest Flutter updates, which adhere to Android/iOS font and screen accessibility requirements.

The APIs currently used on breez mobile will be removed on Flutter. Additionally, we are not calculating font size correctly today on breez mobile, but it is correct on breez cloud. (This is partially correct, as you can see in the video, some areas of the app still don't respect the font settings)

I recorded a video showing how c-breez respects the accessibility settings and how breez mobile doesn’t.

Another aspect of my findings is that I tested three devices and two emulators and didn’t find the same difference you found unless you changed font/screen accessibility. I wonder if you have these settings changed or what kind of screen configuration your device has.


https://github.com/breez/c-breez/assets/1225438/2b66fb81-0111-449e-b87d-7d26aa409b7d

**Comment by kingonly** [comment]
Can you please test on a Pixel 8?

**Comment by kingonly** [comment]
I'm also using these:
![Screenshot_20240104-171755](https://github.com/breez/c-breez/assets/31890660/77204e1f-7990-4113-80b3-f99f8a749530)

**Comment by ademar111190** [comment]
> Can you please test on a Pixel 8?

I'll test on a Pixel 8 simulator (android 14) as I don't have this device to test IRL

**Comment by ademar111190** [comment]
The simulator I created following [these specs](https://support.google.com/pixelphone/answer/7158570?hl=en#zippy=%2Cpixel-pro) shows the same behavior as shown at your screenshots @kingonly once I set these display options you shared

To put that in tangible terms, below is a table comparing breez mobile and cloud breez where the font size being used after the font scale calculation at a given font scale option is registered.

|Font Scale|Breez Mobile|Breez Cloud|
|:-:|:-:|:-:|
|1 (min)|15.882|11.475|
|2 (def)|13.5|13.5|
|3|11.739|15.525|
|4 - 7 (max)|10.384|17.55|

Here I'm using numbers to represent that scale, these numbers are not given by the API, I'm adding these numbers just as a label to make it easier to talk about the scales; The API is designed to receive a font size, and give back to you the pixel size you should use, it doesn't tell you anything about the settings per see.
1 is the minimum, 2 is the default, from 3 up to 6 you have a gradient of increasing options, and finally, at 7 you have the max; Notice that starting from 4 up to 7 there are no changes at the output, that is possible once the [font scale nowadays is non-linear](https://developer.android.com/about/versions/14/features#non-linear-font-scaling).

As you can see, the breez cloud follows the option, i.e. when the user sets a smaller font size to the system it is reduced, when the user increases, it increases. Breez Mobile does the opposite, reduces when it should increase and increases when it should reduce.

**Comment by kingonly** [comment]
I'm closing for now

**Comment by ademar111190** [comment]
I've made this matrix for reference, columns are the display scale (DS) rows are the Fonst Scale (FS) and each screenshot has font variations from 13.5 (our current setup) up to 15.5.

The android default is DS 2 and FS 2; here the snipet to generate this screen https://gist.github.com/ademar111190/deac09eedd06a4ce9e776fff55e33db6

||DS 1|DS 2|DS 3|DS 4|
|:--|:-:|:-:|:-:|:-:|
|FS 1|![ds-1-fs-1](https://github.com/breez/c-breez/assets/1225438/31d6f9ec-bca4-4dce-bea5-a2094442ff3f)|![ds-2-fs-1](https://github.com/breez/c-breez/assets/1225438/3f33b179-91e8-43d6-8f01-08fff2ad7d5f)|![ds-3-fs-1](https://github.com/breez/c-breez/assets/1225438/2a44b353-44aa-42df-9e3a-a75f68018636)|![ds-4-fs-1](https://github.com/breez/c-breez/assets/1225438/b767a755-f88e-4156-a68d-bf1d811f22d3)|
|FS 2|![ds-1-fs-2](https://github.com/breez/c-breez/assets/1225438/9c9e3b4e-8e38-463e-9987-61a9f164f699)|![ds-2-fs-2](https://github.com/breez/c-breez/assets/1225438/f802057d-e981-4764-a380-00b90cb8d291)|![ds-3-fs-2](https://github.com/breez/c-breez/assets/1225438/af4a926a-7568-46ed-a00b-39b14828c00e)|![ds-4-fs-2](https://github.com/breez/c-breez/assets/1225438/1ccc127e-5a90-4a59-a2cc-754d7843543c)|
|FS 3|![ds-1-fs-3](https://github.com/breez/c-breez/assets/1225438/12c2e943-428d-4a96-8359-5e3a3d4b0f48)|![ds-2-fs-3](https://github.com/breez/c-breez/assets/1225438/f1b22e9b-9691-4624-a286-4aca9f7697c1)|![ds-3-fs-3](https://github.com/breez/c-breez/assets/1225438/6dd4c854-2f72-4619-b24f-ea4d5014d896)|![ds-4-fs-3](https://github.com/breez/c-breez/assets/1225438/24a01ed5-721a-4aa3-b299-4ea621ee2389)|
|FS 4|![ds-1-fs-4](https://github.com/breez/c-breez/assets/1225438/aba5930f-6b6c-40ae-8c3c-cd39344e1a05)|![ds-2-fs-4](https://github.com/breez/c-breez/assets/1225438/fd96cb34-dcf8-4097-8cde-f93703afebbc)|![ds-3-fs-4](https://github.com/breez/c-breez/assets/1225438/1ce3a2da-dccd-42a8-871f-d585ccf45e77)|![ds-4-fs-4](https://github.com/breez/c-breez/assets/1225438/3479470b-210f-40a3-9d59-729ac880b276)|
