### ISSUE TITLE
Handle background notifications after app is killed on Android devices

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/c-breez#747]
Basically, we need to

- [ ] Enable autostart
- [ ] Disable battery optimizations

for the app, but it's a bit of a complicated process as there's too many variance from manufacturer to manufacturer and even from device to device of a certain manufacturer...

**Comment by kingonly** [comment]
Not sure that disabling battery optimizations is required (see Phoenix).
Blixt's Lightning Box implemented disable, please review because it seems they are doing it correctly.

**Comment by erdemyerebasmaz** [comment]
@kingonly True, battery optimization isn't required per se but increases reliability afaik. I will be reviewing their implementation 👍 

I may have found a solution that does not require these settings. It's working locally for my device, building the APK for online testing: [Build Android](https://github.com/breez/c-breez/actions/runs/7329368787)
