### ISSUE TITLE
Balance occasionally does not get updated on receiving a payment

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/c-breez#756]
I encounter this mostly when testing offline payments on Android.

Not confirmed yet, but a reproducible case should be:
- Create an invoice
- Scan invoice through WoS
  - or any 3rd party that queues and retries failed payments
- Close the app and then "**Force Stop**" the app from app settings
  - Background service should not handle the notification this way
- Payment will be queued
- Open the app, the payment should go through but the balance does not get updated

There's an example video on #offline-payments channel on Slack.

**Comment by roeierez** [comment]
@erdemyerebasmaz is this still hapenning?

**Comment by erdemyerebasmaz** [comment]
> @erdemyerebasmaz is this still hapenning?

@roeierez I'm unable to test this due to node issues.
Added this case to @Nackoo2000 tests.

**Comment by erdemyerebasmaz** [comment]
I couldn't reproduce. Closing for now.
