### ISSUE TITLE
Openning channels issue

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#767]
When I do a fresh TestFlight version there are no problems opening a channel.

When I have a TestFlight old version and I click Upgrade to the latest one, it signs me out of my wallet and goes back to asking me to create a new one or restore one. Then I have the opening channels issue when I click on a new wallet.

[c-breez.logs (25).zip](https://github.com/breez/c-breez/files/14035834/c-breez.logs.25.zip)

![image](https://github.com/breez/c-breez/assets/127208515/b09c8c90-b53f-43af-a2e5-bcb25c590339)

**Comment by Nackoo2000** [comment]
Now this is happening on every new wallet does not matter if I upgrade or a new installation.

**Comment by erdemyerebasmaz** [comment]
Fixed by #841
