### ISSUE TITLE
UI going blank

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#773]
When I want to close the app in Android and click "NO" on the dialog the screen becomes black.

On an older Android device, the problem does not happen.

![image](https://github.com/breez/c-breez/assets/127208515/9ae326d3-e212-4e59-a5a4-60c194980a5d)

**Comment by ademar111190** [comment]
I've tried on some devices without success; including a modern s22 with Android 14.

Can you share your logs @Nackoo2000  and maybe details on what devices you managed to replicate the bug and what devices you tested that did not experience the bug?

Something like this table would be super useful:

|Device|Android|Bug happens|
|:--|:-:|:-:|
|Samsung S22|14|NO|
|Xiaomi MI A2|11|NO|
|Fire HD 8 plus|Fire OS 7|NO|

**Comment by erdemyerebasmaz** [comment]
This was hotfixed 3 weeks ago dd0dd353aa43ebede28454280605c0bf4c4bfc30 but haven't tested with an Android 13+ device with Predictive back.

@ademar111190 Could you test on Samsung S22 again after enabling [predictive back](https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture#dev-option)?

**Comment by ademar111190** [comment]
Thanks for the context @erdemyerebasmaz 

yeap that is working as expected; I'm closing the issue for now.

@Nackoo2000 feel free to re-open in case you manage to get the error again in the newest build.
