### ISSUE TITLE
Swap-in screen: Error appears unexpectedly

### ISSUE THREAD

**Issue by ok300** [breez/c-breez#789]
Steps to reproduce:
- Go to "Receive via BTC Address" screen
- From a separate wallet, send a valid swap amount to that address
- Within a few seconds, the c-breez UI shows the below error

![Screenshot from 2024-02-20 11-46-18](https://github.com/breez/c-breez/assets/106775972/600f17d1-eee1-4d80-b046-c24ad2c22fbb)

Suggested alternatives:
- this message should not be shown as an error, but more like an info
- c-breez could just navigate away from this screen, as soon as it detects the swap is in progress

**Comment by roeierez** [comment]
@erdemyerebasmaz it seems to me as if  the UI calls `receive_onchain` repeatedly.

**Comment by roeierez** [comment]
The screen should be replaced by a one that shows the swap address with the associate transaction. I think we already have this code but a bug in the polling here makes the code probably call receive_onchain again. @erdemyerebasmaz

**Comment by erdemyerebasmaz** [comment]
fixed by #783 and there are no regression with upcoming changes to in progress swap/reverse swap polling.
