### ISSUE TITLE
Wrong limit on Receive via BTC Address

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#811]
The limit should be 4M sats (this example in the picture is with an empty node).
![image](https://github.com/breez/c-breez/assets/127208515/dc70b405-5f41-4f16-bdb8-e546aef3e5d4)

**Comment by erdemyerebasmaz** [comment]
This value is the maximum allowed deposit amount retrieved from our SwapperAPI and appears to be correct.

@ok300 Please verify.

**Comment by erdemyerebasmaz** [comment]
Depends on:
- https://github.com/breez/breez-sdk/pull/861

**Comment by ok300** [comment]
Yes these values look realistic.

```
sdk> receive_onchain
...
  "min_allowed_deposit": 6228,
  "max_allowed_deposit": 900000,
...
```

**Comment by ok300** [comment]
Looks like https://github.com/breez/breez-sdk/pull/861 will increase the limit to 4M though.

**Comment by roeierez** [comment]
@erdemyerebasmaz @JssDWt  despite this PR is merged, I still see 900k sats limit in the UI in new builds.

**Comment by erdemyerebasmaz** [comment]
> @erdemyerebasmaz @JssDWt  despite this PR is merged, I still see 900k sats limit in the UI in new builds.

Explained in https://github.com/breez/breez-sdk/issues/871

You need to use up your unused swaps that were created before this change to get new values.
