### ISSUE TITLE
First payment on a new node failed (offline receiving invoice)

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#819]
1. Created an invoice
2. Scanned with BreezM
3. Closed BreezC on iOS device
4. Sent the payment from BreezM
5. Notification received in BreezC that the payment failed

![image](https://github.com/breez/c-breez/assets/127208515/804119e6-85d5-4f29-8dc1-429701833715)
[c-breez.logs (32).zip](https://github.com/breez/c-breez/files/14587792/c-breez.logs.32.zip)

BreezM logs:
[lnd (44).log](https://github.com/breez/c-breez/files/14587800/lnd.44.log)

**Comment by Nackoo2000** [comment]
This is a payment to the same node after opening a channel
![image](https://github.com/breez/c-breez/assets/127208515/ad3ef517-8a41-4dda-92ed-74ff83411336)
[c-breez.logs (33).zip](https://github.com/breez/c-breez/files/14587924/c-breez.logs.33.zip)

**Comment by erdemyerebasmaz** [comment]
Hey @Nackoo2000, 
Forgot to mention, when it comes to offline payments, it's really important to know if the error is platform specific or not. Could you check if this is reproducible on Android or it's solely an iOS issue?

**Comment by dangeross** [comment]
Looking at the logs, the `payment_received` notification was received. The plugin connected and waited for an `invoice_paid` event. Nothing was received after 30 seconds and iOS shutdown the service. 

This was on a peak Greenlight congestion day, so I would recommend a retest

**Comment by Nackoo2000** [comment]
The notification on the 6190 looks good.
![image](https://github.com/breez/c-breez/assets/127208515/91d1cf44-a087-4bb8-86e8-c70a27be9641)
[c-breez.logs (48).zip](https://github.com/breez/c-breez/files/14663135/c-breez.logs.48.zip)

**Comment by erdemyerebasmaz** [comment]
> The notification on the 6190 looks good. ![image](https://private-user-images.githubusercontent.com/127208515/314409875-91d1cf44-a087-4bb8-86e8-c70a27be9641.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjQ5NDEsIm5iZiI6MTcxMDkyNDY0MSwicGF0aCI6Ii8xMjcyMDg1MTUvMzE0NDA5ODc1LTkxZDFjZjQ0LWEwODctNGJiOC04NmU4LWM3MGEyN2JlOTY0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwODUwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDE5NjUyZTVhNzdiZjIyOTMwN2U1ODhmMGExZDk0ZWU4MDY5OTE5NTgxNjVmNGZlYjY1M2IxODdlZDc4ODRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IP-9bZ-Kbiy-HC1CBwM4Ynw0OBXBT-NPE9-KgyOV9cQ) [c-breez.logs (48).zip](https://github.com/breez/c-breez/files/14663135/c-breez.logs.48.zip)

> Indeed. The whole notification feature on iOS depends on the fact that payments must be completed in less than 30 seconds. If it is beyond that they will fail as ios extension process will be killed.

Closing as this is a service related issue.
