### ISSUE TITLE
Swap failed

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#822]
On Android device:
When the on-chain transaction was confirmed it did not appear in Breez Cloud.

[c-breez.logs (35).zip](https://github.com/breez/c-breez/files/14599566/c-breez.logs.35.zip)

**Comment by Nackoo2000** [comment]
Swap failed on iOS device:
![image](https://github.com/breez/c-breez/assets/127208515/9861eed7-c0f6-4b21-9dca-328cec37196b)
[c-breez.logs (38).zip](https://github.com/breez/c-breez/files/14602696/c-breez.logs.38.zip)

**Comment by Nackoo2000** [comment]
When I click on the receive via BTC address
![image](https://github.com/breez/c-breez/assets/127208515/a678ed5e-a3ff-4d65-8041-14462bb29b39)

**Comment by roeierez** [comment]
This should be fixed in the new build
