### ISSUE TITLE
LNURL problem with WoS

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#839]
When I scan a LNURL with WoS it does not allow me to edit the amount.
It enters 1 sat for the payment and I can't change it.

https://github.com/breez/c-breez/assets/127208515/4204b3e4-dc29-47cc-b814-8d08ae86c8eb

**Comment by Nackoo2000** [comment]
Same thing happens when I copy and paste the LNURL

**Comment by erdemyerebasmaz** [comment]
Can't reproduce. I'm able to click & edit the amount on WoS.

**Comment by ok300** [comment]
Also can't reproduce if I scan the LNURL QR from c-breez. WoS starts with 1 sat, but I can click it and edit the amount.

**Comment by Nackoo2000** [comment]
OK my mistake closing this one. Just checked.
