### ISSUE TITLE
Let user know if they won't be able to receive payments through their Lightning Address

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/c-breez#843]
Do not show LN Address QR to the user if
- `minSendable` is less than 1 sats, or greater than `maxSendable`
- If `maxSendable` is smaller than `minSendable` due to low fee limit, tell user to increase their fee limit

**Comment by ok300** [comment]
Are these checks not already done in the SDK?

**Comment by erdemyerebasmaz** [comment]
> Are these checks not already done in the SDK?

@ok300 No, not at this stage.

The lightning address is created through [our LNURL server](https://github.com/breez/breez-lnurl) and [it only returns callbackURL](https://github.com/breez/breez-lnurl/blob/86f25e9c98ce8847e14c636d7796d513c08b2a52/lnurl/pay.go#L156). Validation happens on client side. 

For proportional fee of **0.4%** & min opening fee as **3000 sats**;
Let's assume user has set their **automatic channel setup fee limit** to 1 sats and they have no inbound liquidity, their `maxSendable` would be **250 sats**, which would fall below `minSendable`. In this case, the QR code should be hidden and user has to be notified to increase their **automatic channel setup fee limit**

**Comment by ok300** [comment]
I see, makes sense. Thanks.
