### ISSUE TITLE
Scan  button does not recognise the BTC addreess on another BreezC display

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#844]
The example on the video shows that the scan button does not recognise the BTC Address on another BreezC or BreezM app

NOTE: When I try with WoS or Sparrow there is no problem. There it recognises the QR 
When scanning from Send >Send to BTC Address it also works as you can see in the video.

https://github.com/breez/c-breez/assets/127208515/b09f8ce2-37cc-4c6f-b7cc-47d0c920074f

**Comment by erdemyerebasmaz** [comment]
Fixed with 
- https://github.com/breez/breez-sdk/issues/894

https://github.com/breez/c-breez/assets/4012752/9728d97a-5ae6-4797-a2cf-a3e18ba4adc5
