### ISSUE TITLE
Generating BTC Address fail

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#847]
When reopened Receive via BTC Address everything worked.
Can't reproduce.

![image](https://github.com/breez/c-breez/assets/127208515/9de8c85a-1368-4862-8e64-50dba6055dbc)
[c-breez.logs (58).zip](https://github.com/breez/c-breez/files/14704257/c-breez.logs.58.zip)

**Comment by roeierez** [comment]
We will close this once @ok300 pushed the fallback urls for chain service.

**Comment by ok300** [comment]
The fix is merged in the SDK: https://github.com/breez/breez-sdk/pull/898
