### ISSUE TITLE
LNURL-pay: Pre-fill amount with minimum accepted by endpoint

### ISSUE THREAD

**Issue by ok300** [breez/c-breez#849]
When paying to a LNURL-pay endpoint, the first step of the interaction already retrieves the min and max amounts accepted.

Currently, the user is presented with
- an empty input field
- the message "enter an amount between (min) sats and (max) sats"

c-breez should pre-fill the input field with the minimum amount. This is how Phoenix, WoS and others do it.

**Comment by erdemyerebasmaz** [comment]
Personally, I prefer the user experience we provide. I always found it weird it that was filled with 1 sats. These wallets do a poor job of showing the field is editable.

- https://github.com/breez/c-breez/issues/839 is proof of that and I had similar experiences.

and, if you're not going to send 1 sats, the experience is:
- Click amount field,
- Clear amount field,
- Input the amount you'd like to send

Applying this for cases where minimum sendable isn't 1 still has the same issue compared to
- Click amount field,
- Input the amount you'd like to send

--- 

We only pre-fill amount for fixed amount invoices:
| Payer Comment Allowed  | No Payer Comment Allowed |
| ------------- | ------------- |
| <img width="100%" alt="image" src="https://github.com/breez/c-breez/assets/4012752/5d4544b0-75f1-4a1d-886b-927c6eadc9a3"> | <img width="100%" alt="image" src="https://github.com/breez/c-breez/assets/4012752/f0c1b76c-6d7c-4118-84dd-76cdb7aad8ef"> |
