### ISSUE TITLE
Display user friendly messages for “transport error”s

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#852]
I just got a transport error message trying to generate a BTC Address.
I clicked Retry and the address was generated successfully.
[c-breez.logs (62).zip](https://github.com/breez/c-breez/files/14771555/c-breez.logs.62.zip)

**Comment by kingonly** [comment]
Why do we need a user friendly error? What the current UI?

**Comment by kingonly** [comment]
If it looked ok, there's no need to improve it imo

**Comment by ok300** [comment]
Maybe this issue again? #829

**Comment by erdemyerebasmaz** [comment]
_Thanks @ok300_  🙏

@kingonly The screen looks like this:

<img width="50%" alt="image" src="https://github.com/breez/c-breez/assets/4012752/142e85fc-8c3a-428c-9749-99a17f0fd725">

I'm thinking of replacing `transport error` messages with:
```
Failed to retrieve an address from Breez server
Please check your internet connection.
```

**Comment by kingonly** [comment]
The generic error is fine, but I wouldn't hide the actual error. Maybe postfix by "More details: xxx"
