### ISSUE TITLE
Blank screen - Sending to BTC Address

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#855]
1. Sent a transaction to a BTC Address.
2. While the transaction is still pending I open Send to BTC Address Screen

![image](https://github.com/breez/c-breez/assets/127208515/0d265e1d-0b27-4e14-bb62-833074097c23)

**Comment by erdemyerebasmaz** [comment]
@Nackoo2000 Can you attach logs please?

**Comment by Nackoo2000** [comment]
[c-breez.logs.zip](https://github.com/breez/c-breez/files/14774024/c-breez.logs.zip)
