### ISSUE TITLE
Wrong colors on welcome screen

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#868]
The button should be shite with blue font.
The "Restore from backup" text should be white.
Screenshot on 6200.1 iOS build
![image](https://github.com/breez/c-breez/assets/127208515/1e487630-4e99-4c6b-80e1-c17449177305)

**Comment by erdemyerebasmaz** [comment]
Can't reproduce on latest build on both Android & iOS.
<img width="414" alt="image" src="https://github.com/breez/c-breez/assets/4012752/6f7e4d89-5570-48ad-901f-829bd5cf3ab8">

Please test with 6203.1, 6200.1 is not part of release tests.
