### ISSUE TITLE
Wrong message for pending closed channel

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#878]
The numbers are wrong in the dialog message and the $ sign has to be removed.
![image](https://github.com/breez/c-breez/assets/127208515/2eb2f429-cb93-43df-93a9-4de930f86dd5)

**Comment by erdemyerebasmaz** [comment]
@Nackoo2000 This is on Breez mobile.. please re-open on https://github.com/breez/breezmobile/issues.
