### ISSUE TITLE
Send onchain: Payment exceeds the limit (0 sats)

### ISSUE THREAD

**Issue by dangeross** [breez/c-breez#891]
It needs to be clearer to the user what this means. The reality is the lightning balance is less than the minimum send amount  (so the SDK returns min 0, max 0)

The user needs to know:
- the minimum amount that can be sent
- that there is not enough funds to send the minimum amount

[c-breez.logs.zip](https://github.com/breez/c-breez/files/15326441/c-breez.logs.zip)

![Screenshot_20240515_215847](https://github.com/breez/c-breez/assets/551697/78f6f7c5-cea1-4143-8fec-acadee6732d8)

**Comment by erdemyerebasmaz** [comment]
Fixed with: 
- https://github.com/breez/breez-sdk/pull/1037
