### ISSUE TITLE
Fiat page not working

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#894]
https://github.com/breez/c-breez/assets/127208515/8b48fe09-1999-4708-b973-1ad3aa1e2494

[c-breez.logs (7).zip](https://github.com/user-attachments/files/15971333/c-breez.logs.7.zip)

**Comment by erdemyerebasmaz** [comment]
@Nackoo2000 I can't reproduce. Could you let me know if you're still experiencing this issue?

**Comment by Nackoo2000** [comment]
@erdemyerebasmaz now it is even worse - most of the time when I click on the Fiat menu the whole app freezes right then.
A few times it opens the menu and still spins to infinity like before.
[c-breez.logs (11).zip](https://github.com/user-attachments/files/16053328/c-breez.logs.11.zip)

**Comment by dangeross** [comment]
I just tested and the same happened for me. It froze, then going back to the app the screen is black

**Comment by Nackoo2000** [comment]
this issue is still present
[c-breez.logs (14).zip](https://github.com/user-attachments/files/16262104/c-breez.logs.14.zip)

**Comment by erdemyerebasmaz** [comment]
> this issue is still present on this build: https://github.com/breez/c-breez/actions/runs/9960241147 [c-breez.logs (14).zip](https://github.com/user-attachments/files/16262104/c-breez.logs.14.zip)

@Nackoo2000 Could you test on Misty Breez?
[Android-APK](https://github.com/breez/l-breez/actions/runs/10044104332/artifacts/1726719017)

We'll implement the changes here on C-Breez once you confirm the fix.

**Comment by Nackoo2000** [comment]
issue solved, now there is no problem with the fiat screen.
